# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

# Universal compatibility block for all Flutter versions
if File.exist?(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb'))
  flutter_application_path = '../'
  load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path)
else
  require File.expand_path(File.join('packages', 'flutter_tools', 'ios', 'recipes'), flutter_root)
  setup_frameworks
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  if defined?(flutter_install_all_ios_pods)
    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if defined?(flutter_additional_ios_build_settings)
      flutter_additional_ios_build_settings(target)
    end
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_CAMERA=1',
        'PERMISSION_MICROPHONE=1',
      ]
    end
  end
end
